# Generated by Django 5.1.2 on 2024-11-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_task_deadline_task_priority_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
